package dmg.cpanel;

import dmg.company.OnSetCompany;
import dmg.drug.OnSetDrug;
import dmg.company.Company;
import dmg.drug.Drug;
import dmg.drug.DrugDaoImpl;
import dmg.drug.DrugIn;
import dmg.drug.DrugInDao;
import dmg.drug.DrugInDaoImpl;
import java.sql.Date;

import javax.swing.JPopupMenu;

public class ControlPanel extends javax.swing.JFrame {

    private Drug selectedDrug;
    private Company selectedCompany;

    public ControlPanel() {
        initComponents();
        CPController.activeMenu = lbDashboard;
        CPController.headerTitle = headerTitle;
        CPController.setTheme(leftPanel, rightHolder, lbDashboard);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        menusParent = new javax.swing.JPanel();
        lbDashboard = new javax.swing.JLabel();
        menusParent1 = new javax.swing.JPanel();
        lbDrugSale = new javax.swing.JLabel();
        menusParent2 = new javax.swing.JPanel();
        lbInventory = new javax.swing.JLabel();
        menusParent3 = new javax.swing.JPanel();
        lbDrugIn = new javax.swing.JLabel();
        menusParent4 = new javax.swing.JPanel();
        lbExpiring = new javax.swing.JLabel();
        menusParent5 = new javax.swing.JPanel();
        lbExpired = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rightHolder = new javax.swing.JPanel();
        dashboardFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        drugInFrame = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfBid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfBuyPrice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfCompany = new javax.swing.JTextField();
        tfBatchNo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfDrugName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfSalePrice = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnAddDrugin = new javax.swing.JButton();
        btnResetDrugin = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        dcEntry = new com.toedter.calendar.JDateChooser();
        dcMfg = new com.toedter.calendar.JDateChooser();
        dcExpired = new com.toedter.calendar.JDateChooser();
        drugSaleFrame = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        inventoryFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField15 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        expiringFrame = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        expiredFrame = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);

        jPanel3.setBackground(new java.awt.Color(113, 140, 174));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        headerTitle.setBackground(new java.awt.Color(186, 209, 239));
        headerTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(68, 92, 124));
        headerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerTitle.setText("Dashboard");
        headerTitle.setIconTextGap(0);
        headerTitle.setOpaque(true);

        leftPanel.setBackground(new java.awt.Color(113, 140, 174));
        leftPanel.setMinimumSize(new java.awt.Dimension(150, 1023));
        leftPanel.setPreferredSize(new java.awt.Dimension(250, 1023));

        menusParent.setBackground(new java.awt.Color(68, 92, 124));
        menusParent.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent.setPreferredSize(new java.awt.Dimension(250, 80));

        lbDashboard.setBackground(new java.awt.Color(68, 92, 124));
        lbDashboard.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(250, 250, 250));
        lbDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/dashboard.png"))); // NOI18N
        lbDashboard.setText("   Dashboard");
        lbDashboard.setAlignmentX(0.5F);
        lbDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDashboardMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDashboardMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDashboardMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParentLayout = new javax.swing.GroupLayout(menusParent);
        menusParent.setLayout(menusParentLayout);
        menusParentLayout.setHorizontalGroup(
            menusParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menusParentLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(lbDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menusParentLayout.setVerticalGroup(
            menusParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParentLayout.createSequentialGroup()
                .addComponent(lbDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        menusParent1.setBackground(leftPanel.getBackground());
        menusParent1.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent1.setPreferredSize(new java.awt.Dimension(250, 80));

        lbDrugSale.setBackground(new java.awt.Color(153, 153, 153));
        lbDrugSale.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbDrugSale.setForeground(new java.awt.Color(250, 250, 250));
        lbDrugSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/house.png"))); // NOI18N
        lbDrugSale.setText("   Drug Sale");
        lbDrugSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDrugSaleMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDrugSaleMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDrugSaleMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParent1Layout = new javax.swing.GroupLayout(menusParent1);
        menusParent1.setLayout(menusParent1Layout);
        menusParent1Layout.setHorizontalGroup(
            menusParent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbDrugSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menusParent1Layout.setVerticalGroup(
            menusParent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDrugSale, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        menusParent2.setBackground(leftPanel.getBackground());
        menusParent2.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent2.setPreferredSize(new java.awt.Dimension(250, 80));

        lbInventory.setBackground(new java.awt.Color(153, 153, 153));
        lbInventory.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbInventory.setForeground(new java.awt.Color(250, 250, 250));
        lbInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/prescription.png"))); // NOI18N
        lbInventory.setText("   Inventory");
        lbInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbInventoryMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbInventoryMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbInventoryMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbInventoryMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParent2Layout = new javax.swing.GroupLayout(menusParent2);
        menusParent2.setLayout(menusParent2Layout);
        menusParent2Layout.setHorizontalGroup(
            menusParent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menusParent2Layout.setVerticalGroup(
            menusParent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menusParent3.setBackground(leftPanel.getBackground());
        menusParent3.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent3.setPreferredSize(new java.awt.Dimension(250, 80));

        lbDrugIn.setBackground(new java.awt.Color(153, 153, 153));
        lbDrugIn.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbDrugIn.setForeground(new java.awt.Color(250, 250, 250));
        lbDrugIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/medicine.png"))); // NOI18N
        lbDrugIn.setText("  Drug In");
        lbDrugIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDrugInMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDrugInMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDrugInMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParent3Layout = new javax.swing.GroupLayout(menusParent3);
        menusParent3.setLayout(menusParent3Layout);
        menusParent3Layout.setHorizontalGroup(
            menusParent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbDrugIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menusParent3Layout.setVerticalGroup(
            menusParent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDrugIn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        menusParent4.setBackground(leftPanel.getBackground());
        menusParent4.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent4.setPreferredSize(new java.awt.Dimension(250, 80));

        lbExpiring.setBackground(new java.awt.Color(153, 153, 153));
        lbExpiring.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbExpiring.setForeground(new java.awt.Color(250, 250, 250));
        lbExpiring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/shelf-life.png"))); // NOI18N
        lbExpiring.setText("   Expiring");
        lbExpiring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExpiringMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExpiringMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExpiringMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParent4Layout = new javax.swing.GroupLayout(menusParent4);
        menusParent4.setLayout(menusParent4Layout);
        menusParent4Layout.setHorizontalGroup(
            menusParent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbExpiring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menusParent4Layout.setVerticalGroup(
            menusParent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbExpiring, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        menusParent5.setBackground(leftPanel.getBackground());
        menusParent5.setMinimumSize(new java.awt.Dimension(250, 50));
        menusParent5.setPreferredSize(new java.awt.Dimension(250, 80));

        lbExpired.setBackground(new java.awt.Color(153, 153, 153));
        lbExpired.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lbExpired.setForeground(new java.awt.Color(250, 250, 250));
        lbExpired.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/expired.png"))); // NOI18N
        lbExpired.setText("   Expired");
        lbExpired.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExpiredMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExpiredMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExpiredMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout menusParent5Layout = new javax.swing.GroupLayout(menusParent5);
        menusParent5.setLayout(menusParent5Layout);
        menusParent5Layout.setHorizontalGroup(
            menusParent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbExpired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menusParent5Layout.setVerticalGroup(
            menusParent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusParent5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbExpired, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jLabel17.setText("AiPharma");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menusParent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menusParent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menusParent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menusParent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menusParent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menusParent5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addComponent(menusParent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusParent3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusParent1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusParent2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menusParent4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menusParent5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightHolder.setBackground(new java.awt.Color(100, 100, 100));
        rightHolder.setLayout(new java.awt.CardLayout());

        dashboardFrame.setBackground(new java.awt.Color(186, 209, 239));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jPanel2.setBackground(new java.awt.Color(186, 209, 239));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("7200");

        jPanel7.setBackground(new java.awt.Color(113, 140, 174));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Drugs");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jPanel8.setBackground(new java.awt.Color(186, 209, 239));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel3.setText("540020");

        jPanel9.setBackground(new java.awt.Color(113, 140, 174));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("This Month Sale");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(186, 209, 239));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel5.setText("50");

        jPanel11.setBackground(new java.awt.Color(113, 140, 174));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Expiring");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel10);

        jPanel12.setBackground(new java.awt.Color(186, 209, 239));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel7.setText("100");

        jPanel13.setBackground(new java.awt.Color(113, 140, 174));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Expired");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel12);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jPanel5.setBackground(new java.awt.Color(186, 209, 239));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel9.setText("7200");

        jPanel14.setBackground(new java.awt.Color(113, 140, 174));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Customers");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5);

        jPanel15.setBackground(new java.awt.Color(186, 209, 239));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel11.setText("7200");

        jPanel16.setBackground(new java.awt.Color(113, 140, 174));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Companies");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel15);

        jPanel17.setBackground(new java.awt.Color(186, 209, 239));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel13.setText("7200");

        jPanel18.setBackground(new java.awt.Color(113, 140, 174));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Income");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel17);

        jPanel19.setBackground(new java.awt.Color(186, 209, 239));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(113, 140, 174), 1, true));

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel15.setText("7200");

        jPanel20.setBackground(new java.awt.Color(113, 140, 174));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Profit");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel19);

        javax.swing.GroupLayout dashboardFrameLayout = new javax.swing.GroupLayout(dashboardFrame);
        dashboardFrame.setLayout(dashboardFrameLayout);
        dashboardFrameLayout.setHorizontalGroup(
            dashboardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashboardFrameLayout.setVerticalGroup(
            dashboardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        rightHolder.add(dashboardFrame, "card2");

        drugInFrame.setBackground(new java.awt.Color(186, 209, 239));

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel19.setText("Bill ID");

        tfBid.setEditable(false);
        tfBid.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfBid.setMinimumSize(new java.awt.Dimension(30, 27));
        tfBid.setPreferredSize(new java.awt.Dimension(200, 27));
        tfBid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfBidMouseClicked(evt);
            }
        });
        tfBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBidActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel20.setText("Buy Price");

        tfBuyPrice.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfBuyPrice.setMinimumSize(new java.awt.Dimension(30, 27));
        tfBuyPrice.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel21.setText("Quantity");

        tfQuantity.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfQuantity.setMinimumSize(new java.awt.Dimension(30, 27));
        tfQuantity.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel22.setText("Company");

        tfCompany.setEditable(false);
        tfCompany.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfCompany.setMinimumSize(new java.awt.Dimension(30, 27));
        tfCompany.setPreferredSize(new java.awt.Dimension(200, 27));
        tfCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfCompanyMouseClicked(evt);
            }
        });
        tfCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCompanyActionPerformed(evt);
            }
        });

        tfBatchNo.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfBatchNo.setMinimumSize(new java.awt.Dimension(30, 27));
        tfBatchNo.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel23.setText("Entry Date");

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel24.setText("Name");

        tfDrugName.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfDrugName.setMinimumSize(new java.awt.Dimension(30, 27));
        tfDrugName.setPreferredSize(new java.awt.Dimension(200, 27));
        tfDrugName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDrugNameMouseClicked(evt);
            }
        });
        tfDrugName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDrugNameKeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel25.setText("Sale Price");

        tfSalePrice.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tfSalePrice.setMinimumSize(new java.awt.Dimension(30, 27));
        tfSalePrice.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel26.setText("Batch No.");

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel27.setText("Mfg Date");

        jLabel28.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel28.setText("Expired Date");

        btnAddDrugin.setBackground(new java.awt.Color(68, 92, 124));
        btnAddDrugin.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnAddDrugin.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDrugin.setText("Add");
        btnAddDrugin.setMaximumSize(new java.awt.Dimension(120, 40));
        btnAddDrugin.setMinimumSize(new java.awt.Dimension(120, 40));
        btnAddDrugin.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAddDrugin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDruginActionPerformed(evt);
            }
        });

        btnResetDrugin.setBackground(new java.awt.Color(255, 92, 124));
        btnResetDrugin.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnResetDrugin.setText("Reset");
        btnResetDrugin.setMaximumSize(new java.awt.Dimension(120, 40));
        btnResetDrugin.setMinimumSize(new java.awt.Dimension(120, 40));
        btnResetDrugin.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/edit.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/edit.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        dcEntry.setOpaque(false);

        dcMfg.setOpaque(false);

        dcExpired.setOpaque(false);

        javax.swing.GroupLayout drugInFrameLayout = new javax.swing.GroupLayout(drugInFrame);
        drugInFrame.setLayout(drugInFrameLayout);
        drugInFrameLayout.setHorizontalGroup(
            drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugInFrameLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(drugInFrameLayout.createSequentialGroup()
                        .addComponent(btnResetDrugin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDrugin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drugInFrameLayout.createSequentialGroup()
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27)
                            .addComponent(jLabel21))
                        .addGap(39, 39, 39)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(drugInFrameLayout.createSequentialGroup()
                                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfBuyPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addGap(12, 12, 12))
                            .addComponent(dcMfg, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addGap(86, 86, 86)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(drugInFrameLayout.createSequentialGroup()
                                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBatchNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfDrugName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfSalePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addGap(12, 12, 12))
                            .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dcExpired, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(dcEntry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        drugInFrameLayout.setVerticalGroup(
            drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugInFrameLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drugInFrameLayout.createSequentialGroup()
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tfBid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drugInFrameLayout.createSequentialGroup()
                                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(tfBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tfCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(dcMfg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(drugInFrameLayout.createSequentialGroup()
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(tfDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tfSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tfBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(drugInFrameLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel28))
                            .addGroup(drugInFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(drugInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddDrugin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetDrugin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        rightHolder.add(drugInFrame, "card4");

        drugSaleFrame.setBackground(new java.awt.Color(186, 209, 239));

        jPanel6.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "In ID", "Drug Name", "Company Name", "Quantity", "Sale Price", "Total Price", "Expired Date", "Entry Date"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jButton3.setBackground(new java.awt.Color(68, 92, 124));
        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Make Invoice");
        jButton3.setMaximumSize(new java.awt.Dimension(120, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(120, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(120, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(68, 92, 124));
        jButton5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Add");
        jButton5.setMaximumSize(new java.awt.Dimension(120, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(120, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(120, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 92, 124));
        jButton6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton6.setText("Reset");
        jButton6.setMaximumSize(new java.awt.Dimension(120, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(120, 40));
        jButton6.setPreferredSize(new java.awt.Dimension(120, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 241, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout drugSaleFrameLayout = new javax.swing.GroupLayout(drugSaleFrame);
        drugSaleFrame.setLayout(drugSaleFrameLayout);
        drugSaleFrameLayout.setHorizontalGroup(
            drugSaleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        drugSaleFrameLayout.setVerticalGroup(
            drugSaleFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rightHolder.add(drugSaleFrame, "card5");

        inventoryFrame.setBackground(new java.awt.Color(186, 209, 239));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "In ID", "Drug Name", "Company Name", "Buy Price", "Sale Price", "Quantity", "Expired Date", "Entry Date"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        jLabel37.setText("Drug ID");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/edit.png"))); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel18.setText("Sort By : ");

        jLabel39.setText("Expired Date");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/edit.png"))); // NOI18N

        javax.swing.GroupLayout inventoryFrameLayout = new javax.swing.GroupLayout(inventoryFrame);
        inventoryFrame.setLayout(inventoryFrameLayout);
        inventoryFrameLayout.setHorizontalGroup(
            inventoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryFrameLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(16, 16, 16)
                .addComponent(jLabel38)
                .addGap(16, 16, 16))
        );
        inventoryFrameLayout.setVerticalGroup(
            inventoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(inventoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel40)
                    .addGroup(inventoryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jLabel18)
                        .addComponent(jLabel39)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightHolder.add(inventoryFrame, "card3");

        expiringFrame.setBackground(new java.awt.Color(186, 209, 239));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "In ID", "Drug Name", "Company Name", "Buy Price", "Sale Price", "Quantity", "Expired Date", "Entry Date"
            }
        ));
        jTable6.setOpaque(false);
        jScrollPane6.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout expiringFrameLayout = new javax.swing.GroupLayout(expiringFrame);
        expiringFrame.setLayout(expiringFrameLayout);
        expiringFrameLayout.setHorizontalGroup(
            expiringFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
            .addGroup(expiringFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(expiringFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        expiringFrameLayout.setVerticalGroup(
            expiringFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(expiringFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(expiringFrameLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        rightHolder.add(expiringFrame, "card6");

        expiredFrame.setBackground(new java.awt.Color(186, 209, 239));

        jLabel33.setText("Expired after: ");

        jLabel34.setText("25/10/2020");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/dateicon.png"))); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "In ID", "Drug Name", "Company Name", "Buy Price", "Sale Price", "Quantity", "Expired Date", "Entry Date"
            }
        ));
        jTable5.setOpaque(false);
        jScrollPane5.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout expiredFrameLayout = new javax.swing.GroupLayout(expiredFrame);
        expiredFrame.setLayout(expiredFrameLayout);
        expiredFrameLayout.setHorizontalGroup(
            expiredFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expiredFrameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        expiredFrameLayout.setVerticalGroup(
            expiredFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expiredFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(expiredFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(expiredFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jLabel34))
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        rightHolder.add(expiredFrame, "card7");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dmg/images/settings.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(headerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel41)
                        .addGap(30, 30, 30))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel41)))
                .addComponent(rightHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInventoryMouseClicked
        CPController.clicked(evt, inventoryFrame);

    }//GEN-LAST:event_lbInventoryMouseClicked

    private void lbDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDashboardMouseClicked
        CPController.clicked(evt, dashboardFrame);

    }//GEN-LAST:event_lbDashboardMouseClicked

    private void lbInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInventoryMouseEntered

        CPController.entered(evt);
    }//GEN-LAST:event_lbInventoryMouseEntered

    private void lbInventoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInventoryMouseReleased

    }//GEN-LAST:event_lbInventoryMouseReleased

    private void lbInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbInventoryMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbInventoryMouseExited

    private void lbDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDashboardMouseEntered
        CPController.entered(evt);
    }//GEN-LAST:event_lbDashboardMouseEntered

    private void lbDrugInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugInMouseClicked
        CPController.clicked(evt, drugInFrame);
    }//GEN-LAST:event_lbDrugInMouseClicked

    private void lbDrugInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugInMouseEntered
        CPController.entered(evt);
    }//GEN-LAST:event_lbDrugInMouseEntered

    private void lbDrugSaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugSaleMouseEntered
        CPController.entered(evt);
    }//GEN-LAST:event_lbDrugSaleMouseEntered

    private void lbExpiringMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiringMouseEntered
        CPController.entered(evt);
    }//GEN-LAST:event_lbExpiringMouseEntered

    private void lbDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDashboardMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbDashboardMouseExited

    private void lbDrugInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugInMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbDrugInMouseExited

    private void lbDrugSaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugSaleMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbDrugSaleMouseExited

    private void lbExpiringMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiringMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbExpiringMouseExited

    private void lbExpiredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiredMouseClicked
        CPController.clicked(evt, expiredFrame);
    }//GEN-LAST:event_lbExpiredMouseClicked

    private void lbExpiringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiringMouseClicked
        CPController.clicked(evt, expiringFrame);
    }//GEN-LAST:event_lbExpiringMouseClicked

    private void lbExpiredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiredMouseEntered
        CPController.entered(evt);
    }//GEN-LAST:event_lbExpiredMouseEntered

    private void lbExpiredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExpiredMouseExited
        CPController.exited(evt);
    }//GEN-LAST:event_lbExpiredMouseExited

    private void lbDrugSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrugSaleMouseClicked
        CPController.clicked(evt, drugSaleFrame);
    }//GEN-LAST:event_lbDrugSaleMouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        final JPopupMenu menu = new JPopupMenu("Menu");
        menu.add("Drug ID");
        menu.add("Drug Name");
        menu.add("Company Name");
        menu.show(jLabel38, jLabel38.getWidth() / 2, jLabel38.getHeight() / 2);


    }//GEN-LAST:event_jLabel38MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked

        //   JPopupMenu pop = new JPopupMenu();
        //  pop.add(datePanel);
        //  pop.show(this, this.getX(), this.getY() + this.getHeight());
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked

        CPController.addCompany();


    }//GEN-LAST:event_jLabel32MouseClicked

    private void tfCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCompanyActionPerformed

    }//GEN-LAST:event_tfCompanyActionPerformed


    private void tfCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCompanyMouseClicked

        CPController.companySelect(new OnSetCompany() {
            @Override
            public void SetCompany(Company company) {
                System.out.println("company selected");
                tfCompany.setText(company.getName());
                selectedCompany = company;
            }
        });

    }//GEN-LAST:event_tfCompanyMouseClicked


    private void btnAddDruginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDruginActionPerformed

        DrugIn drugin = new DrugIn(
                selectedDrug.getId(),
                Double.parseDouble(tfBuyPrice.getText()),
                Double.parseDouble(tfSalePrice.getText()),
                Integer.parseInt(tfQuantity.getText()),
                Integer.parseInt(tfBatchNo.getText()),
                selectedCompany.getId(),
                new Date(dcEntry.getDate().getTime()),
                new Date(dcExpired.getDate().getTime()),
                new Date(dcMfg.getDate().getTime())
        );

        CPController.addDrugIn(drugin);

    }//GEN-LAST:event_btnAddDruginActionPerformed

    private void tfDrugNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDrugNameKeyPressed

    }//GEN-LAST:event_tfDrugNameKeyPressed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        CPController.addDrug();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void tfDrugNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDrugNameMouseClicked
        CPController.drugSelect(new OnSetDrug() {

            @Override
            public void SetDrug(Drug drug) {
                Company company = drug.getCompany(drug.getId());

                tfDrugName.setText(drug.getName());
                tfBuyPrice.setText(String.valueOf(drug.getBuyprice()));
                tfSalePrice.setText(String.valueOf(drug.getSaleprice()));
                tfCompany.setText(company.getName());
                selectedDrug = drug;
                selectedCompany = company;
            }
        });
    }//GEN-LAST:event_tfDrugNameMouseClicked

    private void tfBidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBidMouseClicked
        DrugInDao daodin = new DrugInDaoImpl();
        tfBid.setText(String.valueOf(daodin.getNextBillId()));
    }//GEN-LAST:event_tfBidMouseClicked

    private void tfBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBidActionPerformed
 
        
    }//GEN-LAST:event_tfBidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugin;
    private javax.swing.JButton btnResetDrugin;
    private javax.swing.JPanel dashboardFrame;
    private com.toedter.calendar.JDateChooser dcEntry;
    private com.toedter.calendar.JDateChooser dcExpired;
    private com.toedter.calendar.JDateChooser dcMfg;
    private javax.swing.JPanel drugInFrame;
    private javax.swing.JPanel drugSaleFrame;
    private javax.swing.JPanel expiredFrame;
    private javax.swing.JPanel expiringFrame;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JPanel inventoryFrame;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbDrugIn;
    private javax.swing.JLabel lbDrugSale;
    private javax.swing.JLabel lbExpired;
    private javax.swing.JLabel lbExpiring;
    private javax.swing.JLabel lbInventory;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel menusParent;
    private javax.swing.JPanel menusParent1;
    private javax.swing.JPanel menusParent2;
    private javax.swing.JPanel menusParent3;
    private javax.swing.JPanel menusParent4;
    private javax.swing.JPanel menusParent5;
    private javax.swing.JPanel rightHolder;
    private javax.swing.JTextField tfBatchNo;
    private javax.swing.JTextField tfBid;
    private javax.swing.JTextField tfBuyPrice;
    private javax.swing.JTextField tfCompany;
    private javax.swing.JTextField tfDrugName;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfSalePrice;
    // End of variables declaration//GEN-END:variables

}
